<?php

namespace NilPortugues\Tests\Api\JsonApi\Integrations\Doctrine\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
}
